/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PlaylistController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Musica;
import model.Playlist;

/**
 *
 * @author aluno.saolucas
 */
public class FrAcePlaylist extends javax.swing.JDialog {

    private Playlist playlistAtual;

    /**
     * Creates new form FrAcePlaylist
     */
    public FrAcePlaylist(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        edtFiltro = new javax.swing.JTextField();
        btnAcessar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlaylist = new javax.swing.JTable();
        btnAddMusica = new javax.swing.JButton();
        btnRemMusica = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acessar Playlist");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipal.setBackground(new java.awt.Color(48, 48, 48));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Acessar Playlist");
        pnlPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(0, 151, 178));
        btnCancelar.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltar.png"))); // NOI18N
        btnCancelar.setText("Voltar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        edtFiltro.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        pnlPrincipal.add(edtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, -1));

        btnAcessar.setBackground(new java.awt.Color(0, 151, 178));
        btnAcessar.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        btnAcessar.setForeground(new java.awt.Color(255, 255, 255));
        btnAcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pesquisar.png"))); // NOI18N
        btnAcessar.setText("Acessar");
        btnAcessar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcessarMouseClicked(evt);
            }
        });
        btnAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnAcessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 116, 120, 30));

        tblPlaylist.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        tblPlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Música", "Artista"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPlaylist.setGridColor(new java.awt.Color(48, 48, 48));
        tblPlaylist.setSelectionForeground(new java.awt.Color(48, 48, 48));
        jScrollPane1.setViewportView(tblPlaylist);

        pnlPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 216, 450, 140));

        btnAddMusica.setBackground(new java.awt.Color(0, 151, 178));
        btnAddMusica.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        btnAddMusica.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mais.png"))); // NOI18N
        btnAddMusica.setText("Adicionar Música");
        btnAddMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMusicaActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnAddMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        btnRemMusica.setBackground(new java.awt.Color(0, 151, 178));
        btnRemMusica.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        btnRemMusica.setForeground(new java.awt.Color(255, 255, 255));
        btnRemMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lixo.png"))); // NOI18N
        btnRemMusica.setText("Remover Música");
        btnRemMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemMusicaActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnRemMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        getContentPane().add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 0, 480, 440));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/musica.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAcessarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcessarMouseClicked

    }//GEN-LAST:event_btnAcessarMouseClicked

    private void btnAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarActionPerformed
        String nome = edtFiltro.getText().trim();
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o nome da playlist!");
            return;
        }

        PlaylistController controller = new PlaylistController();
        playlistAtual = controller.buscarPorNome(nome);

        if (playlistAtual == null) {
            JOptionPane.showMessageDialog(this, "Playlist não encontrada!");
        } else {
            carregarTabela(playlistAtual.getMusicas());
        }
    }//GEN-LAST:event_btnAcessarActionPerformed

    private void btnAddMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMusicaActionPerformed
        if (playlistAtual == null) {
        JOptionPane.showMessageDialog(this, "Acesse uma playlist primeiro!");
        return;
    }

    // Aqui usamos diretamente o id da playlistAtual
    int idPlaylist = playlistAtual.getPkplaylist();

    FrAddMusica dialog = new FrAddMusica(null, true);
    dialog.setIdPlaylist(idPlaylist);
    dialog.setVisible(true);

    // Atualizar a tabela após adicionar músicas
    PlaylistController controller = new PlaylistController();
    playlistAtual.setMusicas(controller.buscarMusicasDaPlaylist(idPlaylist));
    carregarTabela(playlistAtual.getMusicas());
    }//GEN-LAST:event_btnAddMusicaActionPerformed

    private void btnRemMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemMusicaActionPerformed
        if (playlistAtual == null) {
            JOptionPane.showMessageDialog(this, "Acesse uma playlist primeiro!");
            return;
        }

        int linha = tblPlaylist.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma música para remover!");
            return;
        }

        int idMusica = (int) tblPlaylist.getValueAt(linha, 0);

        PlaylistController controller = new PlaylistController();
        boolean ok = controller.removerMusicaDaPlaylist(playlistAtual.getPkplaylist(), idMusica);

        if (ok) {
            JOptionPane.showMessageDialog(this, "Música removida!");
            playlistAtual.setMusicas(controller.buscarMusicasDaPlaylist(playlistAtual.getPkplaylist()));
            carregarTabela(playlistAtual.getMusicas());
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao remover música!");
        }
    }//GEN-LAST:event_btnRemMusicaActionPerformed

    private void carregarTabela(List<Musica> musicas) {
        DefaultTableModel modelo = (DefaultTableModel) tblPlaylist.getModel();
        modelo.setRowCount(0);

        for (Musica m : musicas) {
            modelo.addRow(new Object[]{
                m.getPkmusica(),
                m.getTitulo(),
                m.getArtistas() != null ? m.getArtistas() : "",
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAcePlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAcePlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAcePlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAcePlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrAcePlaylist dialog = new FrAcePlaylist(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessar;
    private javax.swing.JButton btnAddMusica;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRemMusica;
    private javax.swing.JTextField edtFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTable tblPlaylist;
    // End of variables declaration//GEN-END:variables
}
