/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MusicaController;
import javax.swing.JOptionPane;
import model.Musica;

/**
 *
 * @author aluno.saolucas
 */
public class FrCadMusica extends javax.swing.JDialog {

    public FrCadMusica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        edtTitulo = new javax.swing.JTextField();
        edtDuracao = new javax.swing.JTextField();
        edtGenero = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        lblDuracao = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        edtAno = new javax.swing.JFormattedTextField();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Música");

        pnlPrincipal.setBackground(new java.awt.Color(48, 48, 48));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastrar Música");
        pnlPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        edtTitulo.setBackground(new java.awt.Color(76, 76, 76));
        edtTitulo.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        edtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        edtTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlPrincipal.add(edtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 320, -1));

        edtDuracao.setBackground(new java.awt.Color(76, 76, 76));
        edtDuracao.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        edtDuracao.setForeground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.add(edtDuracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 320, -1));

        edtGenero.setBackground(new java.awt.Color(76, 76, 76));
        edtGenero.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        edtGenero.setForeground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.add(edtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 320, -1));

        lblTitulo.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Título");
        pnlPrincipal.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        lblDuracao.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblDuracao.setForeground(new java.awt.Color(255, 255, 255));
        lblDuracao.setText("Duração");
        pnlPrincipal.add(lblDuracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        lblGenero.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblGenero.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero.setText("Gênero");
        pnlPrincipal.add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        lblAno.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblAno.setForeground(new java.awt.Color(255, 255, 255));
        lblAno.setText("Ano");
        pnlPrincipal.add(lblAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        edtAno.setBackground(new java.awt.Color(76, 76, 76));
        edtAno.setForeground(new java.awt.Color(255, 255, 255));
        edtAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy"))));
        edtAno.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        pnlPrincipal.add(edtAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 150, 30));

        btnCancelar.setBackground(new java.awt.Color(0, 151, 178));
        btnCancelar.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        btnSalvar.setBackground(new java.awt.Color(0, 151, 178));
        btnSalvar.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/musica.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        gravarMusica();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void gravarMusica() {
        if (!verificarCamposMusica()) {
            return;
        }

        Musica m = new Musica();
        m.setTitulo(edtTitulo.getText());
        m.setDuracao(edtDuracao.getText());
        m.setGenero(edtGenero.getText());
        m.setAno(Integer.parseInt(edtAno.getText()));

        MusicaController controller = new MusicaController();
        if (controller.inserir(m)) {
            JOptionPane.showMessageDialog(null, "Música inserida");
            this.dispose(); 
        }
    }

    private boolean verificarCamposMusica() {
        if (edtTitulo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo 'título' em branco");
            return false;
        }
        if (edtDuracao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo 'duração' em branco");
            return false;
        }
        if (edtGenero.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo 'gênero' em branco");
            return false;
        }
        if (edtAno.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo 'ano' em branco");
            return false;
        }
        try {
            Integer.parseInt(edtAno.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ano inválido");
            return false;
        }
        
        return true;
    }


    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadMusica.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadMusica.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadMusica.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadMusica.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrCadMusica dialog = new FrCadMusica(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JFormattedTextField edtAno;
    private javax.swing.JTextField edtDuracao;
    private javax.swing.JTextField edtGenero;
    private javax.swing.JTextField edtTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblDuracao;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
